name: Run Tests and Linting

on:
  pull_request:
    branches:
      - master

jobs:
  deploy:
    name: Run Adapter Tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Checkout Ref
        uses: actions/checkout@v1
        # ref is not set as it should be using master only
      - name: Run Tests
        working-directory: ./packages/analytics-adapter/
        run: npm run test

