name: Run Tests

on:
  push:
    paths:
      - 'packages/analytics-adapter/**'

jobs:
  deploy:
    name: Run Adapter Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          registry-url: 'https://registry.npmjs.org'

      - name: Run Tests
        working-directory: ./packages/analytics-adapter/
        run: |
          npm install
          npm run test
